### ISSUE TITLE
Prevent bot from reporting its own pixel placement twice

### ISSUE THREAD

**Issue by Mismatchia** [traa-pixelcanvas/TraanvasBot#17]
Currently whenever the bot places a pixel, it doesn't know to ignore that pixel when checking changes on the canvas to print out. 

Ex:
```
>> 14:40:09 ->Somebody updated 139176,-22470 with turquoise
>> 14:40:09 ->You painted turquoise at 139176,-22470
```

**Comment by Mismatchia** [comment]
Solved by cf359e2477697e7cc83ce8ba57e79615e8ef6a55.

**Comment by capn-geek** [comment]
Still having some problems with a few pixels being reported twice. See the log below for several examples over a period of time.

```
>> 07:40:24 ->You painted turquoise at 139226,-22453
>> 07:40:24 ->Waiting 11.2 seconds
>> 07:40:24 ->Somebody updated 139226,-22453 with turquoise
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:40:37 ->You painted turquoise at 139227,-22453
>> 07:40:37 ->Waiting 10.6 seconds
[+++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:40:48 ->You painted turquoise at 139228,-22453
>> 07:40:48 ->Waiting 10.9 seconds
[++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:41:01 ->You painted turquoise at 139229,-22453
>> 07:41:01 ->Waiting 11.2 seconds
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:41:13 ->You painted turquoise at 139230,-22453
>> 07:41:13 ->Waiting 10.9 seconds
>> 07:41:13 ->Somebody updated 139230,-22453 with turquoise
[++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:41:26 ->You painted turquoise at 139231,-22453
>> 07:41:26 ->Waiting 10.6 seconds
[+++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:41:38 ->You painted turquoise at 139232,-22453
>> 07:41:38 ->Waiting 11.2 seconds
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:41:50 ->You painted turquoise at 139233,-22453
>> 07:41:50 ->Waiting 10.9 seconds
>> 07:41:50 ->Somebody updated 139233,-22453 with turquoise
[++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:42:02 ->You painted turquoise at 139235,-22453
>> 07:42:02 ->Waiting 11.2 seconds
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:42:15 ->You painted turquoise at 139237,-22453
>> 07:42:15 ->Waiting 11.2 seconds
>> 07:42:15 ->Somebody updated 139237,-22453 with turquoise
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:42:27 ->You painted turquoise at 139240,-22453
>> 07:42:27 ->Waiting 11.2 seconds
>> 07:42:27 ->Somebody updated 139240,-22453 with turquoise
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:42:40 ->You painted turquoise at 139242,-22453
>> 07:42:40 ->Waiting 11.2 seconds
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:42:52 ->You painted turquoise at 139244,-22453
>> 07:42:52 ->Waiting 11.2 seconds
>> 07:42:52 ->Somebody updated 139244,-22453 with turquoise
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:43:05 ->You painted turquoise at 139245,-22453
>> 07:43:05 ->Waiting 11.2 seconds
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:43:17 ->You painted turquoise at 139248,-22453
>> 07:43:17 ->Waiting 10.9 seconds
[++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:43:29 ->You painted turquoise at 139249,-22453
>> 07:43:29 ->Waiting 10.9 seconds
>> 07:43:29 ->Somebody updated 139249,-22453 with turquoise
[++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:43:42 ->You painted turquoise at 139251,-22453
>> 07:43:42 ->Waiting 11.2 seconds
>> 07:43:42 ->Somebody updated 139251,-22453 with turquoise
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:43:54 ->You painted turquoise at 139252,-22453
>> 07:43:54 ->Waiting 10.6 seconds
>> 07:43:54 ->Somebody updated 139252,-22453 with turquoise
[+++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:44:06 ->You painted turquoise at 139253,-22453
>> 07:44:06 ->Waiting 10.6 seconds
>> 07:44:06 ->Somebody updated 139253,-22453 with turquoise
[+++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:44:18 ->You painted turquoise at 139254,-22453
>> 07:44:18 ->Waiting 10.89 seconds
[++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:44:30 ->You painted turquoise at 139255,-22453
>> 07:44:30 ->Waiting 11.2 seconds
>> 07:44:30 ->Somebody updated 139255,-22453 with turquoise
[+++++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:44:43 ->You painted black at 139256,-22453
>> 07:44:43 ->Waiting 10.6 seconds
>> 07:44:43 ->Somebody updated 139256,-22453 with black
[+++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:44:55 ->You painted pink at 139257,-22453
>> 07:44:55 ->Waiting 10.59 seconds
[+++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 07:45:07 ->You painted pink at 139258,-22453
>> 07:45:07 ->Waiting 10.6 seconds
>> 07:45:07 ->Somebody updated 139258,-22453 with pink
[+++++++++++++++++++++++++++++++++++++++++++++++++++]
```

**Comment by Mismatchia** [comment]
Double reporting cause by lag should be fixed by 9d2104e54b4cd393ac63786971fa45ee864d861b.

However, some people are still getting some double messages before the bot receives a success message. 
![bug](https://user-images.githubusercontent.com/49257776/55670284-12967880-58ca-11e9-87c5-afad53ec6f82.png)

**Comment by Mismatchia** [comment]
Issue should be fixed by ba027574019be1e1d13ce85e49a4b32fd51ae2c8
